name = "rhel-9-latest-PCI-DSS"
description = "Latest RHEL 9.x release and erratum with PCI-DSS OpenSCAP Security Profile"
version = "0.0.3"
modules = []
groups = []
distro = ""

[[packages]]
name = "firewalld"

[[packages]]
name = "openscap-scanner"

[[packages]]
name = "openscap-utils"

[[packages]]
name = "scap-security-guide"

[customizations]
hostname = "rhel9latest-pci-dss-template"

[[customizations.sshkey]]
user = "root"
key = "ssh-rsa AAAAB3NzvuwYHjcfSMwvNj9dvrec0V demo"

[[customizations.user]]
name = "myadmin"
password = "$6$VWQ0E6MeWexjFlnt$Yaeq3eN0kD3NN0"
key = "ssh-rsa AAAAB3NzvuwYHjcfSMwvNj9dvrec0V demo"
groups = ["wheel"]

[customizations.timezone]
timezone = "America/Indiana/Indianapolis"
ntpservers = ["0.rhel.pool.ntp.org", "1.rhel.pool.ntp.org"]

[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "us"

[customizations.firewall]
[customizations.firewall.services]
enabled = ["ssh"]

[customizations.services]
enabled = ["sshd", "crond", "firewalld", "systemd-journald", "rsyslog", "auditd"]
disabled = ["nfs-server", "rpcbind"]

[customizations.openscap]
datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml"
profile_id = "xccdf_org.ssgproject.content_profile_pci-dss"

[[customizations.filesystem]]
mountpoint = "/home"
size = 1073741824

[[customizations.filesystem]]
mountpoint = "/tmp"
size = 1073741824

[[customizations.filesystem]]
mountpoint = "/var"
size = 3221225472

[[customizations.filesystem]]
mountpoint = "/var/log"
size = 5368709120

[[customizations.filesystem]]
mountpoint = "/var/log/audit"
size = 10737418240

[[customizations.filesystem]]
mountpoint = "/var/tmp"
size = 1073741824

[[customizations.filesystem]]
mountpoint = "/"
size = 10737418240

