###############################################################################
#
# Blueprint for Health Insurance Portability and Accountability Act (HIPAA)
#
# Profile Description:
# The HIPAA Security Rule establishes U.S. national standards to protect individuals’
# electronic personal health information that is created, received, used, or
# maintained by a covered entity. The Security Rule requires appropriate
# administrative, physical and technical safeguards to ensure the
# confidentiality, integrity, and security of electronic protected health
# information.
# This profile configures Red Hat Enterprise Linux 9 to the HIPAA Security
# Rule identified for securing of electronic protected health information.
# Use of this profile in no way guarantees or makes claims against legal compliance against the HIPAA Security Rule(s).
#
# Profile ID:  xccdf_org.ssgproject.content_profile_hipaa
# Benchmark ID:  xccdf_org.ssgproject.content_benchmark_RHEL-9
# Benchmark Version:  0.1.69
# XCCDF Version:  1.2
#
# This file was generated by OpenSCAP 1.3.8 using:
# $ oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_hipaa --fix-type blueprint xccdf-file.xml
#
# This Blueprint is generated from an OpenSCAP profile without preliminary evaluation.
# It attempts to fix every selected rule, even if the system is already compliant.
#
# How to apply this Blueprint:
# composer-cli blueprints push blueprint.toml
#
# See RHEL documentation for more customization options. 
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/composing_a_customized_rhel_system_image/index#composer-blueprint-format_creating-system-images-with-composer-command-line-interface
#
# oscap info /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
# oscap info --profiles /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
# oscap info --profile xccdf_org.ssgproject.content_profile_hipaa /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
# oscap xccdf generate fix --profile xccdf_org.ssgproject.content_profile_hipaa --fix-type blueprint /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
# 
# Note:  When importing into image builder, all comment lines will be removed.
###############################################################################

name = "RHEL-9-latest-HIPAA"
description = "Blueprint for Health Insurance Portability and Accountability Act (HIPAA) from profile xccdf_org.ssgproject.content_profile_hipaa and auditable by Red Hat Insights."
version = "0.0.1"
modules = []
groups = []
distro = ""

[customizations.openscap]
datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml"
profile_id = "xccdf_org.ssgproject.content_profile_hipaa"

[[packages]]
name = "audit"

[[packages]]
name = "scap-security-guide"

[[packages]]
name = "insights-client"

[[packages]]
name = "rhc"

[[packages]]
name = "rhc-worker-playbook"

[[packages]]
name = "glibc-langpack-en"

[[packages]]
name = "langpacks-en"

[[packages]]
name = "ansible-core"

[[packages]]
name = "rhel-system-roles"

[customizations.kernel]
append = "audit=1"

[customizations.firewall]
[customizations.firewall.services]
enabled = ["ssh"]

[customizations.services]
enabled = ["sshd", "crond", "auditd"]
disabled = ["telnet","rlogin","xinetd","kdump","autofs","debug-shell"]
#enabled = ["sshd", "cronyd", "firewalld", "systemd-journald", "rsyslog", "auditd"]

# The below add up to a 10 GB disk size.  Adjust according to deployment environment.
#[[customizations.filesystem]]
#mountpoint = "/"
#minsize = "4 GB"
#
#[[customizations.filesystem]]
#mountpoint = "/home"
#size =  "1 GB"
#
#[[customizations.filesystem]]
#mountpoint = "/tmp"
#size =  "1 GB"
#
#[[customizations.filesystem]]
#mountpoint = "/var"
#size =  "1 GB"
#
#[[customizations.filesystem]]
#mountpoint = "/var/log"
#size =  "1 GB"
#
#[[customizations.filesystem]]
#mountpoint = "/var/log/audit"
#size =  "1 GB"
#
#[[customizations.filesystem]]
#mountpoint = "/var/tmp"
#size =  "1 GB"
#
